spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-route
              uri: lb://product-service
              predicates:
                - Path=/api/products/**
              filters:
                - name: AuthFilter
                  args: {}
            - id: order-route
              uri: lb://order-service
              predicates:
                - Path=/api/orders/**
              filters:
                - name: AuthFilter
                  args: {}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8700